language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=24
    - ANDROID_BUILD_TOOLS=24.0.2
android:
 components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
    - chmod +x gradelew
    - ./gradlew dependencies || true
script:
    - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
