language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=24
    - ANDROID_BUILD_TOOLS=24.0.2
android:
 components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
    - chmod +x gradlew
    - ./gradlew dependencies || true
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script:
    - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
deploy:
  provider: releases
  file: Project.apk
  skip_cleanup: true

  on:
    repo: patelhr/Project
    tags: true
    jdk: oraclejdk8
  api_key:
    secure:"kUrq3qh4qEQCLWE7VcTud9MIPbe9kpu5dGCjOpgKi9OlvrsGJpbCZwbzsRMS+U4uqM3e0QfCVRDb/QksVqnq4DTwCChR0CKUAFa2SB5ZI8iP21hst/jOmXzCjYkzuGLaTQSGCl+vdLCFclDERmN/3deMWsDxSekA7bV9V2L4lJDvRIO2Hln979q6E6Ljp8HI7cJvF6wpYaAWZU6QJCG7QLydTUoH5CfADoHKWOhn87mHX/kMmlIi1kTVqCGwO5nQa6v13f3nfR+ZdsA5dh6c+k+ECE5yZyL1vQcxuTPdnHL+dHw/bcKdqRIkZslM+0WOb+UXDzOc20ltXJnMJSLjn3lxojiT2oNu/0Xk7GFQ0Kp6Hd6F5vl5RrTgSDXq4xePTuCvFoekOLJbTG0VdQhYiK93HLR5rK52Wn6HmhqAcrTG6VleS+NNeLHFqsDfqCGhji+5JQrNZpXtb1PJaM3w3dVEBeeaNoqGnpEZoShh35FX5ain7y+C7dy06D6Zm35S4jeAiXWSvkxzIto8abM+eDVMrYxHayQntrRdOmjgDKlbp69hDCdVDLv9jz4PJQz7E0baPXeZtYiyfMt83gt5UvT8E1duPqYl9atACRLdPml2B7ca7fsAVlFPO2RN+sM7ytDDgzHv+SScTDCCKKU44auibcMZfy4Q9uEKYWb4l3I="